version: "2.1"

services:
  aok_product_dev:
    build:
      context: .
      dockerfile: dev.df
    image: aok_product:dev
    entrypoint: /bin/ash
    stdin_open: true
    tty: true
    env_file: .env
    volumes:
      - .:/app
